databases:
  - name: mini-order-db
    plan: free
    databaseName: mini_order_db

services:
  - type: web
    name: mini-order-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mini-order-db
          property: connectionString
